//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EservicesAPI.InvoiceWoodSrv {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseSimpleObject", Namespace="http://schemas.datacontract.org/2004/07/NRA.DataModel")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EservicesAPI.InvoiceWoodSrv.RevenueClassifiers))]
    public partial class BaseSimpleObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RevenueClassifiers", Namespace="http://schemas.datacontract.org/2004/07/NRA.DataModel")]
    [System.SerializableAttribute()]
    public partial class RevenueClassifiers : EservicesAPI.InvoiceWoodSrv.BaseSimpleObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EservicesAPI.InvoiceWoodSrv.SawProductList SawProductsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EservicesAPI.InvoiceWoodSrv.SpecieList SpeciesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EservicesAPI.InvoiceWoodSrv.SawProductList SawProducts {
            get {
                return this.SawProductsField;
            }
            set {
                if ((object.ReferenceEquals(this.SawProductsField, value) != true)) {
                    this.SawProductsField = value;
                    this.RaisePropertyChanged("SawProducts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EservicesAPI.InvoiceWoodSrv.SpecieList Species {
            get {
                return this.SpeciesField;
            }
            set {
                if ((object.ReferenceEquals(this.SpeciesField, value) != true)) {
                    this.SpeciesField = value;
                    this.RaisePropertyChanged("Species");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="SawProductList", Namespace="http://schemas.datacontract.org/2004/07/NRA.DataModel", ItemName="SawProduct")]
    [System.SerializableAttribute()]
    public class SawProductList : System.Collections.Generic.List<EservicesAPI.InvoiceWoodSrv.SawProduct> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="SpecieList", Namespace="http://schemas.datacontract.org/2004/07/NRA.DataModel", ItemName="Specie")]
    [System.SerializableAttribute()]
    public class SpecieList : System.Collections.Generic.List<EservicesAPI.InvoiceWoodSrv.Specie> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SawProduct", Namespace="http://schemas.datacontract.org/2004/07/NRA.DataModel")]
    [System.SerializableAttribute()]
    public partial class SawProduct : EservicesAPI.InvoiceWoodSrv.SimpleClassifier {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MeasurementTypeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SawMillProductTypeIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MeasurementTypeID {
            get {
                return this.MeasurementTypeIDField;
            }
            set {
                if ((this.MeasurementTypeIDField.Equals(value) != true)) {
                    this.MeasurementTypeIDField = value;
                    this.RaisePropertyChanged("MeasurementTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SawMillProductTypeID {
            get {
                return this.SawMillProductTypeIDField;
            }
            set {
                if ((this.SawMillProductTypeIDField.Equals(value) != true)) {
                    this.SawMillProductTypeIDField = value;
                    this.RaisePropertyChanged("SawMillProductTypeID");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseObject", Namespace="http://schemas.datacontract.org/2004/07/NRA.DataModel")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EservicesAPI.InvoiceWoodSrv.SimpleClassifier))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EservicesAPI.InvoiceWoodSrv.Specie))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EservicesAPI.InvoiceWoodSrv.Quality))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EservicesAPI.InvoiceWoodSrv.SawProduct))]
    public partial class BaseObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] VersionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Version {
            get {
                return this.VersionField;
            }
            set {
                if ((object.ReferenceEquals(this.VersionField, value) != true)) {
                    this.VersionField = value;
                    this.RaisePropertyChanged("Version");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SimpleClassifier", Namespace="http://schemas.datacontract.org/2004/07/NRA.DataModel")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EservicesAPI.InvoiceWoodSrv.Specie))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EservicesAPI.InvoiceWoodSrv.Quality))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EservicesAPI.InvoiceWoodSrv.SawProduct))]
    public partial class SimpleClassifier : EservicesAPI.InvoiceWoodSrv.BaseObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TypeCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TypeCode {
            get {
                return this.TypeCodeField;
            }
            set {
                if ((this.TypeCodeField.Equals(value) != true)) {
                    this.TypeCodeField = value;
                    this.RaisePropertyChanged("TypeCode");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Specie", Namespace="http://schemas.datacontract.org/2004/07/NRA.DataModel")]
    [System.SerializableAttribute()]
    public partial class Specie : EservicesAPI.InvoiceWoodSrv.SimpleClassifier {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid GroupIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GroupNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EservicesAPI.InvoiceWoodSrv.QualityList QualitiesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid GroupID {
            get {
                return this.GroupIDField;
            }
            set {
                if ((this.GroupIDField.Equals(value) != true)) {
                    this.GroupIDField = value;
                    this.RaisePropertyChanged("GroupID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GroupName {
            get {
                return this.GroupNameField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupNameField, value) != true)) {
                    this.GroupNameField = value;
                    this.RaisePropertyChanged("GroupName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderNum {
            get {
                return this.OrderNumField;
            }
            set {
                if ((this.OrderNumField.Equals(value) != true)) {
                    this.OrderNumField = value;
                    this.RaisePropertyChanged("OrderNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EservicesAPI.InvoiceWoodSrv.QualityList Qualities {
            get {
                return this.QualitiesField;
            }
            set {
                if ((object.ReferenceEquals(this.QualitiesField, value) != true)) {
                    this.QualitiesField = value;
                    this.RaisePropertyChanged("Qualities");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Quality", Namespace="http://schemas.datacontract.org/2004/07/NRA.DataModel")]
    [System.SerializableAttribute()]
    public partial class Quality : EservicesAPI.InvoiceWoodSrv.SimpleClassifier {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="QualityList", Namespace="http://schemas.datacontract.org/2004/07/NRA.DataModel", ItemName="Quality")]
    [System.SerializableAttribute()]
    public class QualityList : System.Collections.Generic.List<EservicesAPI.InvoiceWoodSrv.Quality> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserFault", Namespace="http://schemas.datacontract.org/2004/07/NRA.DataModel")]
    [System.SerializableAttribute()]
    public partial class UserFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SystemInternalFault", Namespace="http://schemas.datacontract.org/2004/07/NRA.DataModel")]
    [System.SerializableAttribute()]
    public partial class SystemInternalFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SessionFault", Namespace="http://schemas.datacontract.org/2004/07/NRA.DataModel")]
    [System.SerializableAttribute()]
    public partial class SessionFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RevenueDocument", Namespace="http://schemas.datacontract.org/2004/07/NRA.DataModel.Services")]
    [System.SerializableAttribute()]
    public partial class RevenueDocument : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DocumentTypeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DocumentTypeID {
            get {
                return this.DocumentTypeIDField;
            }
            set {
                if ((this.DocumentTypeIDField.Equals(value) != true)) {
                    this.DocumentTypeIDField = value;
                    this.RaisePropertyChanged("DocumentTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NO {
            get {
                return this.NOField;
            }
            set {
                if ((object.ReferenceEquals(this.NOField, value) != true)) {
                    this.NOField = value;
                    this.RaisePropertyChanged("NO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BalanceServiceInfo", Namespace="http://schemas.datacontract.org/2004/07/NRA.DataModel.Services")]
    [System.SerializableAttribute()]
    public partial class BalanceServiceInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid DetailIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSocialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OwnerIdenticalNOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OwnerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SpecieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal VolumeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid DetailID {
            get {
                return this.DetailIDField;
            }
            set {
                if ((this.DetailIDField.Equals(value) != true)) {
                    this.DetailIDField = value;
                    this.RaisePropertyChanged("DetailID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSocial {
            get {
                return this.IsSocialField;
            }
            set {
                if ((this.IsSocialField.Equals(value) != true)) {
                    this.IsSocialField = value;
                    this.RaisePropertyChanged("IsSocial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NO {
            get {
                return this.NOField;
            }
            set {
                if ((object.ReferenceEquals(this.NOField, value) != true)) {
                    this.NOField = value;
                    this.RaisePropertyChanged("NO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OwnerIdenticalNO {
            get {
                return this.OwnerIdenticalNOField;
            }
            set {
                if ((object.ReferenceEquals(this.OwnerIdenticalNOField, value) != true)) {
                    this.OwnerIdenticalNOField = value;
                    this.RaisePropertyChanged("OwnerIdenticalNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OwnerName {
            get {
                return this.OwnerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OwnerNameField, value) != true)) {
                    this.OwnerNameField = value;
                    this.RaisePropertyChanged("OwnerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductType {
            get {
                return this.ProductTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductTypeField, value) != true)) {
                    this.ProductTypeField = value;
                    this.RaisePropertyChanged("ProductType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Specie {
            get {
                return this.SpecieField;
            }
            set {
                if ((object.ReferenceEquals(this.SpecieField, value) != true)) {
                    this.SpecieField = value;
                    this.RaisePropertyChanged("Specie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Volume {
            get {
                return this.VolumeField;
            }
            set {
                if ((this.VolumeField.Equals(value) != true)) {
                    this.VolumeField = value;
                    this.RaisePropertyChanged("Volume");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SpendingProductServiceInfo", Namespace="http://schemas.datacontract.org/2004/07/NRA.DataModel.Services")]
    [System.SerializableAttribute()]
    public partial class SpendingProductServiceInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid DetailIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> DiameterLargeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> DiameterSmallField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdenticalNOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSocialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> LengthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MarkerNOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime OriginDocDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OriginDocNOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SpecieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal VolumeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid DetailID {
            get {
                return this.DetailIDField;
            }
            set {
                if ((this.DetailIDField.Equals(value) != true)) {
                    this.DetailIDField = value;
                    this.RaisePropertyChanged("DetailID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> DiameterLarge {
            get {
                return this.DiameterLargeField;
            }
            set {
                if ((this.DiameterLargeField.Equals(value) != true)) {
                    this.DiameterLargeField = value;
                    this.RaisePropertyChanged("DiameterLarge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> DiameterSmall {
            get {
                return this.DiameterSmallField;
            }
            set {
                if ((this.DiameterSmallField.Equals(value) != true)) {
                    this.DiameterSmallField = value;
                    this.RaisePropertyChanged("DiameterSmall");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdenticalNO {
            get {
                return this.IdenticalNOField;
            }
            set {
                if ((object.ReferenceEquals(this.IdenticalNOField, value) != true)) {
                    this.IdenticalNOField = value;
                    this.RaisePropertyChanged("IdenticalNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSocial {
            get {
                return this.IsSocialField;
            }
            set {
                if ((this.IsSocialField.Equals(value) != true)) {
                    this.IsSocialField = value;
                    this.RaisePropertyChanged("IsSocial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Length {
            get {
                return this.LengthField;
            }
            set {
                if ((this.LengthField.Equals(value) != true)) {
                    this.LengthField = value;
                    this.RaisePropertyChanged("Length");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MarkerNO {
            get {
                return this.MarkerNOField;
            }
            set {
                if ((object.ReferenceEquals(this.MarkerNOField, value) != true)) {
                    this.MarkerNOField = value;
                    this.RaisePropertyChanged("MarkerNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime OriginDocDate {
            get {
                return this.OriginDocDateField;
            }
            set {
                if ((this.OriginDocDateField.Equals(value) != true)) {
                    this.OriginDocDateField = value;
                    this.RaisePropertyChanged("OriginDocDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OriginDocNO {
            get {
                return this.OriginDocNOField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginDocNOField, value) != true)) {
                    this.OriginDocNOField = value;
                    this.RaisePropertyChanged("OriginDocNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Specie {
            get {
                return this.SpecieField;
            }
            set {
                if ((object.ReferenceEquals(this.SpecieField, value) != true)) {
                    this.SpecieField = value;
                    this.RaisePropertyChanged("Specie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Volume {
            get {
                return this.VolumeField;
            }
            set {
                if ((this.VolumeField.Equals(value) != true)) {
                    this.VolumeField = value;
                    this.RaisePropertyChanged("Volume");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateInvoiceResult", Namespace="http://schemas.datacontract.org/2004/07/NRA.DataModel.Services")]
    [System.SerializableAttribute()]
    public partial class CreateInvoiceResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EservicesAPI.InvoiceWoodSrv.RevenueDocumentDetails[] ProblematicDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EservicesAPI.InvoiceWoodSrv.RevenueDocumentDetails[] ProblematicDetails {
            get {
                return this.ProblematicDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProblematicDetailsField, value) != true)) {
                    this.ProblematicDetailsField = value;
                    this.RaisePropertyChanged("ProblematicDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RevenueDocumentDetails", Namespace="http://schemas.datacontract.org/2004/07/NRA.DataModel.Services")]
    [System.SerializableAttribute()]
    public partial class RevenueDocumentDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommonCommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DocumentTypeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductValidationErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SpecieValidationErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VolumeValidationErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CommonComment {
            get {
                return this.CommonCommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommonCommentField, value) != true)) {
                    this.CommonCommentField = value;
                    this.RaisePropertyChanged("CommonComment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DocumentTypeID {
            get {
                return this.DocumentTypeIDField;
            }
            set {
                if ((this.DocumentTypeIDField.Equals(value) != true)) {
                    this.DocumentTypeIDField = value;
                    this.RaisePropertyChanged("DocumentTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductValidationError {
            get {
                return this.ProductValidationErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductValidationErrorField, value) != true)) {
                    this.ProductValidationErrorField = value;
                    this.RaisePropertyChanged("ProductValidationError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SpecieValidationError {
            get {
                return this.SpecieValidationErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.SpecieValidationErrorField, value) != true)) {
                    this.SpecieValidationErrorField = value;
                    this.RaisePropertyChanged("SpecieValidationError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VolumeValidationError {
            get {
                return this.VolumeValidationErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.VolumeValidationErrorField, value) != true)) {
                    this.VolumeValidationErrorField = value;
                    this.RaisePropertyChanged("VolumeValidationError");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="InvoiceWoodSrv.IRevenueService")]
    public interface IRevenueService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRevenueService/GetClassifiers", ReplyAction="http://tempuri.org/IRevenueService/GetClassifiersResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EservicesAPI.InvoiceWoodSrv.UserFault), Action="http://tempuri.org/IRevenueService/GetClassifiersUserFaultFault", Name="UserFault", Namespace="http://schemas.datacontract.org/2004/07/NRA.DataModel")]
        [System.ServiceModel.FaultContractAttribute(typeof(EservicesAPI.InvoiceWoodSrv.SystemInternalFault), Action="http://tempuri.org/IRevenueService/GetClassifiersSystemInternalFaultFault", Name="SystemInternalFault", Namespace="http://schemas.datacontract.org/2004/07/NRA.DataModel")]
        [System.ServiceModel.FaultContractAttribute(typeof(EservicesAPI.InvoiceWoodSrv.SessionFault), Action="http://tempuri.org/IRevenueService/GetClassifiersSessionFaultFault", Name="SessionFault", Namespace="http://schemas.datacontract.org/2004/07/NRA.DataModel")]
        EservicesAPI.InvoiceWoodSrv.RevenueClassifiers GetClassifiers(string SecurityToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRevenueService/GetClassifiers", ReplyAction="http://tempuri.org/IRevenueService/GetClassifiersResponse")]
        System.Threading.Tasks.Task<EservicesAPI.InvoiceWoodSrv.RevenueClassifiers> GetClassifiersAsync(string SecurityToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRevenueService/GetRevenueDocumentsByIdentNO", ReplyAction="http://tempuri.org/IRevenueService/GetRevenueDocumentsByIdentNOResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EservicesAPI.InvoiceWoodSrv.UserFault), Action="http://tempuri.org/IRevenueService/GetRevenueDocumentsByIdentNOUserFaultFault", Name="UserFault", Namespace="http://schemas.datacontract.org/2004/07/NRA.DataModel")]
        [System.ServiceModel.FaultContractAttribute(typeof(EservicesAPI.InvoiceWoodSrv.SystemInternalFault), Action="http://tempuri.org/IRevenueService/GetRevenueDocumentsByIdentNOSystemInternalFaul" +
            "tFault", Name="SystemInternalFault", Namespace="http://schemas.datacontract.org/2004/07/NRA.DataModel")]
        [System.ServiceModel.FaultContractAttribute(typeof(EservicesAPI.InvoiceWoodSrv.SessionFault), Action="http://tempuri.org/IRevenueService/GetRevenueDocumentsByIdentNOSessionFaultFault", Name="SessionFault", Namespace="http://schemas.datacontract.org/2004/07/NRA.DataModel")]
        EservicesAPI.InvoiceWoodSrv.RevenueDocument[] GetRevenueDocumentsByIdentNO(string SecurityToken, string IdentNO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRevenueService/GetRevenueDocumentsByIdentNO", ReplyAction="http://tempuri.org/IRevenueService/GetRevenueDocumentsByIdentNOResponse")]
        System.Threading.Tasks.Task<EservicesAPI.InvoiceWoodSrv.RevenueDocument[]> GetRevenueDocumentsByIdentNOAsync(string SecurityToken, string IdentNO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRevenueService/GetBalance", ReplyAction="http://tempuri.org/IRevenueService/GetBalanceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EservicesAPI.InvoiceWoodSrv.UserFault), Action="http://tempuri.org/IRevenueService/GetBalanceUserFaultFault", Name="UserFault", Namespace="http://schemas.datacontract.org/2004/07/NRA.DataModel")]
        [System.ServiceModel.FaultContractAttribute(typeof(EservicesAPI.InvoiceWoodSrv.SystemInternalFault), Action="http://tempuri.org/IRevenueService/GetBalanceSystemInternalFaultFault", Name="SystemInternalFault", Namespace="http://schemas.datacontract.org/2004/07/NRA.DataModel")]
        [System.ServiceModel.FaultContractAttribute(typeof(EservicesAPI.InvoiceWoodSrv.SessionFault), Action="http://tempuri.org/IRevenueService/GetBalanceSessionFaultFault", Name="SessionFault", Namespace="http://schemas.datacontract.org/2004/07/NRA.DataModel")]
        EservicesAPI.InvoiceWoodSrv.BalanceServiceInfo[] GetBalance(string SecurityToken, string NO, string IdentNO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRevenueService/GetBalance", ReplyAction="http://tempuri.org/IRevenueService/GetBalanceResponse")]
        System.Threading.Tasks.Task<EservicesAPI.InvoiceWoodSrv.BalanceServiceInfo[]> GetBalanceAsync(string SecurityToken, string NO, string IdentNO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRevenueService/GetProductsBySpending", ReplyAction="http://tempuri.org/IRevenueService/GetProductsBySpendingResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EservicesAPI.InvoiceWoodSrv.UserFault), Action="http://tempuri.org/IRevenueService/GetProductsBySpendingUserFaultFault", Name="UserFault", Namespace="http://schemas.datacontract.org/2004/07/NRA.DataModel")]
        [System.ServiceModel.FaultContractAttribute(typeof(EservicesAPI.InvoiceWoodSrv.SystemInternalFault), Action="http://tempuri.org/IRevenueService/GetProductsBySpendingSystemInternalFaultFault", Name="SystemInternalFault", Namespace="http://schemas.datacontract.org/2004/07/NRA.DataModel")]
        [System.ServiceModel.FaultContractAttribute(typeof(EservicesAPI.InvoiceWoodSrv.SessionFault), Action="http://tempuri.org/IRevenueService/GetProductsBySpendingSessionFaultFault", Name="SessionFault", Namespace="http://schemas.datacontract.org/2004/07/NRA.DataModel")]
        EservicesAPI.InvoiceWoodSrv.SpendingProductServiceInfo[] GetProductsBySpending(string SecurityToken, string OriginDocNO, string IdentNO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRevenueService/GetProductsBySpending", ReplyAction="http://tempuri.org/IRevenueService/GetProductsBySpendingResponse")]
        System.Threading.Tasks.Task<EservicesAPI.InvoiceWoodSrv.SpendingProductServiceInfo[]> GetProductsBySpendingAsync(string SecurityToken, string OriginDocNO, string IdentNO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRevenueService/CreateInvoce", ReplyAction="http://tempuri.org/IRevenueService/CreateInvoceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EservicesAPI.InvoiceWoodSrv.UserFault), Action="http://tempuri.org/IRevenueService/CreateInvoceUserFaultFault", Name="UserFault", Namespace="http://schemas.datacontract.org/2004/07/NRA.DataModel")]
        [System.ServiceModel.FaultContractAttribute(typeof(EservicesAPI.InvoiceWoodSrv.SystemInternalFault), Action="http://tempuri.org/IRevenueService/CreateInvoceSystemInternalFaultFault", Name="SystemInternalFault", Namespace="http://schemas.datacontract.org/2004/07/NRA.DataModel")]
        [System.ServiceModel.FaultContractAttribute(typeof(EservicesAPI.InvoiceWoodSrv.SessionFault), Action="http://tempuri.org/IRevenueService/CreateInvoceSessionFaultFault", Name="SessionFault", Namespace="http://schemas.datacontract.org/2004/07/NRA.DataModel")]
        EservicesAPI.InvoiceWoodSrv.CreateInvoiceResult CreateInvoce(string SecurityToken, string XMLData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRevenueService/CreateInvoce", ReplyAction="http://tempuri.org/IRevenueService/CreateInvoceResponse")]
        System.Threading.Tasks.Task<EservicesAPI.InvoiceWoodSrv.CreateInvoiceResult> CreateInvoceAsync(string SecurityToken, string XMLData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRevenueService/CancelInvoce", ReplyAction="http://tempuri.org/IRevenueService/CancelInvoceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EservicesAPI.InvoiceWoodSrv.UserFault), Action="http://tempuri.org/IRevenueService/CancelInvoceUserFaultFault", Name="UserFault", Namespace="http://schemas.datacontract.org/2004/07/NRA.DataModel")]
        [System.ServiceModel.FaultContractAttribute(typeof(EservicesAPI.InvoiceWoodSrv.SystemInternalFault), Action="http://tempuri.org/IRevenueService/CancelInvoceSystemInternalFaultFault", Name="SystemInternalFault", Namespace="http://schemas.datacontract.org/2004/07/NRA.DataModel")]
        [System.ServiceModel.FaultContractAttribute(typeof(EservicesAPI.InvoiceWoodSrv.SessionFault), Action="http://tempuri.org/IRevenueService/CancelInvoceSessionFaultFault", Name="SessionFault", Namespace="http://schemas.datacontract.org/2004/07/NRA.DataModel")]
        bool CancelInvoce(string SecurityToken, string InvoceNO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRevenueService/CancelInvoce", ReplyAction="http://tempuri.org/IRevenueService/CancelInvoceResponse")]
        System.Threading.Tasks.Task<bool> CancelInvoceAsync(string SecurityToken, string InvoceNO);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRevenueServiceChannel : EservicesAPI.InvoiceWoodSrv.IRevenueService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RevenueServiceClient : System.ServiceModel.ClientBase<EservicesAPI.InvoiceWoodSrv.IRevenueService>, EservicesAPI.InvoiceWoodSrv.IRevenueService {
        
        public RevenueServiceClient() {
        }
        
        public RevenueServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RevenueServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RevenueServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RevenueServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EservicesAPI.InvoiceWoodSrv.RevenueClassifiers GetClassifiers(string SecurityToken) {
            return base.Channel.GetClassifiers(SecurityToken);
        }
        
        public System.Threading.Tasks.Task<EservicesAPI.InvoiceWoodSrv.RevenueClassifiers> GetClassifiersAsync(string SecurityToken) {
            return base.Channel.GetClassifiersAsync(SecurityToken);
        }
        
        public EservicesAPI.InvoiceWoodSrv.RevenueDocument[] GetRevenueDocumentsByIdentNO(string SecurityToken, string IdentNO) {
            return base.Channel.GetRevenueDocumentsByIdentNO(SecurityToken, IdentNO);
        }
        
        public System.Threading.Tasks.Task<EservicesAPI.InvoiceWoodSrv.RevenueDocument[]> GetRevenueDocumentsByIdentNOAsync(string SecurityToken, string IdentNO) {
            return base.Channel.GetRevenueDocumentsByIdentNOAsync(SecurityToken, IdentNO);
        }
        
        public EservicesAPI.InvoiceWoodSrv.BalanceServiceInfo[] GetBalance(string SecurityToken, string NO, string IdentNO) {
            return base.Channel.GetBalance(SecurityToken, NO, IdentNO);
        }
        
        public System.Threading.Tasks.Task<EservicesAPI.InvoiceWoodSrv.BalanceServiceInfo[]> GetBalanceAsync(string SecurityToken, string NO, string IdentNO) {
            return base.Channel.GetBalanceAsync(SecurityToken, NO, IdentNO);
        }
        
        public EservicesAPI.InvoiceWoodSrv.SpendingProductServiceInfo[] GetProductsBySpending(string SecurityToken, string OriginDocNO, string IdentNO) {
            return base.Channel.GetProductsBySpending(SecurityToken, OriginDocNO, IdentNO);
        }
        
        public System.Threading.Tasks.Task<EservicesAPI.InvoiceWoodSrv.SpendingProductServiceInfo[]> GetProductsBySpendingAsync(string SecurityToken, string OriginDocNO, string IdentNO) {
            return base.Channel.GetProductsBySpendingAsync(SecurityToken, OriginDocNO, IdentNO);
        }
        
        public EservicesAPI.InvoiceWoodSrv.CreateInvoiceResult CreateInvoce(string SecurityToken, string XMLData) {
            return base.Channel.CreateInvoce(SecurityToken, XMLData);
        }
        
        public System.Threading.Tasks.Task<EservicesAPI.InvoiceWoodSrv.CreateInvoiceResult> CreateInvoceAsync(string SecurityToken, string XMLData) {
            return base.Channel.CreateInvoceAsync(SecurityToken, XMLData);
        }
        
        public bool CancelInvoce(string SecurityToken, string InvoceNO) {
            return base.Channel.CancelInvoce(SecurityToken, InvoceNO);
        }
        
        public System.Threading.Tasks.Task<bool> CancelInvoceAsync(string SecurityToken, string InvoceNO) {
            return base.Channel.CancelInvoceAsync(SecurityToken, InvoceNO);
        }
    }
}
